#!/usr/local/bin/perl -Tw

use Apache ();
use strict;
use vars qw($Scalar @Array %Hash); #for testing perl-status

$Scalar = 1;
@Array  = qw(one two three);
%Hash   = map { $_, $Scalar++ } @Array;

my $r = Apache->request;
%ENV = $r->cgi_env;

$r->content_type("text/html");
$r->send_http_header;

my(@args);

if (@args = $r->args) {
    $r->write_client(
       "ARGS: ",
       join(", ", map { $_ = qq{"$_"} } @args),
       "\n\n");
} else {
    $r->write_client("No command line arguments passed to script\n\n");
}

my($key,$val);
while (($key,$val) = each %ENV) {
   $r->print("$key=$val\n");
}

if ($ENV{CONTENT_LENGTH}) {
    #$len = $ENV{CONTENT_LENGTH};
    my $content = $r->content;
    
    $r->print("\nContent\n-------\n$content");
}
