=head1 NAME

CHANGES

=head1 Description

Refer to this document to learn what changes were made to the
documents, since you've read these last time. 

The most recent changes are listed first.

=head1 Sat Sep 15 19:45:41 SGT 2001

* templates::choosing, the initial version added (Perrin Harkins
  E<lt>perrin@elem.comE<gt>)

  o E<lt>perrin@elem.comE<gt>)

  o E<lt>perrin@elem.comE<gt>)

templates::choosing, the initial version added (Perrin Harkins

* templates::choosing, the initial version added (Perrin Harkins
  E<lt>perrin@elem.comE<gt>)
  E<lt>perrin@elem.comE<gt>)
  E<lt>perrin@elem.comE<gt>)
templates::choosing, the initial version added (Perrin Harkins



=cut

