=head1 NAME

Getting Your Feet Wet with mod_perl

=head1 Description

This chapter gives you the bare minimum information to get you started
with mod_perl.

=head1 A Quick Guide to Getting Started with mod_perl

META: to be written

=head1 Maintainers

Maintainer is the person(s) you should contact with updates,
corrections and patches.

=over

=item *

=back


=head1 Authors

=over

=item *

=back

Only the major authors are listed above. For contributors see the
Changes file.


=cut
