=head1 NAME

Coding with and for mod_perl

=head1 Description

FIXME: DESCRIPTION


=head1 Prerequisites

=head1 Installing from Source

=head1 Installing from Binary Packages

=head1 Perl Specifics in mod_perl Environment

In the following sections we discuss the specifics of Perl behavior
under mod_perl.

=head2 exit()

In the normal Perl code exit() is used to stop the program flow and
exit the Perl interpreter. However under mod_perl we only want the
stop the program flow without killing the Perl interpreter.

You should take no action if your code includes exit() calls and it's
OK to continue using them. mod_perl worries to override the exit()
function with its own version which stops the program flow, and
performs all the necessary cleanups, but doesn't kill the server. This
is done by overriding:

  *CORE::GLOBAL::exit = \&ModPerl::Util::exit;

so if you mess up with C<*CORE::GLOBAL::exit> yourself you better know
what you are doing.

You can still call C<CORE::exit> to kill the interpreter, again if you
know what you are doing.

=head1 Maintainers

Maintainer is the person(s) you should contact with updates,
corrections and patches.

=over

=item *

=back


=head1 Authors

=over

=item *

=back

Only the major authors are listed above. For contributors see the
Changes file.



=cut
