=head1 NAME

ModPerl::Util -- Helper mod_perl 2.0 Functions

=head1 SYNOPSIS

  use ModPerl::Util;
  
  $callback = Apache::current_callback;
  
  ModPerl::Util::exit();
  
  ModPerl::Util::untaint($) # secret API?

=head1 DESCRIPTION

C<ModPerl::Util> provides mod_perl 2.0 util functions.

=head1 API

=over

=item * current_callback

Returns the currently running callback, like 'PerlResponseHandler'

=item * exit

Used internally to replace CORE::exit and terminate the request,
not the current process.

=back

=cut
